### ISSUE TITLE
[CLOSED] Replace document repository

### ISSUE THREAD

**Issue by benilovj** [alphagov/specialist-publisher#183]
<a href="https://github.com/evilstreak"><img src="https://avatars.githubusercontent.com/u/74812?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [evilstreak](https://github.com/evilstreak)**
_Thursday 24 July 2014 at 14:46 GMT_
_Originally opened as https://github.com/alphagov/specialist-publisher/pull/183_

---

These commits move from storing document editions as standalone records to storing them embedded in a document record.

This will allow us to do more sane queries against the data, which will make providing features like pagination so we can handle 10,000 imported documents much simpler.
## Tasks
- [x] Write a migration to copy data from the old collection into the new collection
- [x] Remove the unused repository and model
- [ ] Tests for the new repository and model

---

_**[evilstreak](https://github.com/evilstreak)** included the following code: https://github.com/alphagov/specialist-publisher/pull/183/commits_

**Comment by benilovj** [comment]
<a href="https://github.com/bestie"><img src="https://avatars.githubusercontent.com/u/145723?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bestie](https://github.com/bestie)**
_Thursday 31 July 2014 at 14:13 GMT_

---

The repository and persistence code is well tested by our acceptance tests at present and there are still some hacks in there to support transitioning to documents behaving more like manuals.

I suggest we don't write the unit tests until the next refactor.

**Comment by benilovj** [comment]
<a href="https://github.com/evilstreak"><img src="https://avatars.githubusercontent.com/u/74812?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [evilstreak](https://github.com/evilstreak)**
_Friday 01 August 2014 at 08:14 GMT_

---

:+1: This looks good. It needs a rebase, and then I think we should do a branch deploy to preview early next week and wail on the existing data a bit.

**Comment by benilovj** [comment]
<a href="https://github.com/bestie"><img src="https://avatars.githubusercontent.com/u/145723?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [bestie](https://github.com/bestie)**
_Tuesday 12 August 2014 at 15:08 GMT_

---

I believe this PR does not degrade functionality as it is currently impossible to roll back a document's attachments.

**Comment by benilovj** [comment]
<a href="https://github.com/kalleth"><img src="https://avatars.githubusercontent.com/u/615627?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [kalleth](https://github.com/kalleth)**
_Wednesday 17 September 2014 at 15:35 GMT_

---

I think I've just performed a successful rebase on branch https://github.com/alphagov/specialist-publisher/compare/replace-document-repository-rebased -- but it could use a review before force pushing to this branch @evilstreak @bestie

**Comment by benilovj** [comment]
<a href="https://github.com/evilstreak"><img src="https://avatars.githubusercontent.com/u/74812?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [evilstreak](https://github.com/evilstreak)**
_Thursday 25 September 2014 at 08:34 GMT_

---

Closing until we make time to revisit this work.
