### ISSUE TITLE
[CLOSED] Add a new document type "Vehicle Recalls and Faults alert"

### ISSUE THREAD

**Issue by benilovj** [alphagov/specialist-publisher#480]
<a href="https://github.com/tadast"><img src="https://avatars.githubusercontent.com/u/218239?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [tadast](https://github.com/tadast)**
_Friday 01 May 2015 at 15:13 GMT_
_Originally opened as https://github.com/alphagov/specialist-publisher/pull/480_

---

This new document type is an attempt by @keithiopia and me to replace the archaic vehicle recalls tool http://www.dft.gov.uk/vosa/apps/recalls, as suggested by someone in the organisations that owns the current tool. 

This is just a MVP to see how well finders are suited to solve this problem. We would ideally need to add more manufacturers, potentially grouped by "Item type" (not sure what's the best way to implement it though)

I also needed to update `gds-sso` gem, because it depends on a newer version of `govuk_content_models`, which needs to be updated due to a new artefact type.

Ideally we'd like to test this in a preview environment, but since the data gets wiped every night it is not ideal. Any suggestions how best to try it out?

It's my first PR on specialist-publisher, so please review carefully :)
## Todo before merging
- [x] Release a new version of govuk_content_models gem with [this change](https://github.com/alphagov/govuk_content_models/pull/300)
- [x] update govuk_content_models version in panopticon
- [x] update govuk_content_models version in specialist-publisher (this PR?)
- [x] add new document type schema to rummager 

---

_**[tadast](https://github.com/tadast)** included the following code: https://github.com/alphagov/specialist-publisher/pull/480/commits_

**Comment by benilovj** [comment]
<a href="https://github.com/keithiopia"><img src="https://avatars.githubusercontent.com/u/7126294?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [keithiopia](https://github.com/keithiopia)**
_Friday 01 May 2015 at 15:24 GMT_

---

We can get around that preview/testing issue by creating drafts in the production environment then publishing in preview.

**Comment by benilovj** [comment]
<a href="https://github.com/tadast"><img src="https://avatars.githubusercontent.com/u/218239?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tadast](https://github.com/tadast)**
_Tuesday 05 May 2015 at 11:16 GMT_

---

Comments addressed, anything else? :)

**Comment by benilovj** [comment]
<a href="https://github.com/tadast"><img src="https://avatars.githubusercontent.com/u/218239?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [tadast](https://github.com/tadast)**
_Wednesday 06 May 2015 at 15:46 GMT_

---

I've completed the checklist in the PR description and addressed all the comments. Can we merge this please?
